# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sjpay' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for sjpay
  pod 'Masonry', '~> 1.1.0'
  pod 'AFNetworking', '~> 3.2.0'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'Reachability', '~> 3.2'
  pod 'BlocksKit', '~> 2.2.5'
  pod 'WechatOpenSDK', '~> 1.8.2'
target 'sjpayTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sjpayUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
